# - name: Configuring {{component}} Repository
#   ansible.builtin.copy:
#     src: redis.repo                                           # Location of the file on the machine where you're running this cript
#     dest: /etc/yum.repos.d/redis.repo                       # Location of the file where you want to copy this to remote server.

# - name: Installing {{component}} package
#   ansible.builtin.package:
#     name: redis-6.2.13 
#     state: present 

# - name: Enabling {{component}} visibility
#   ansible.builtin.replace:
#     path: /etc/redis.conf
#     regexp: '127.0.0.1'
#     replace: '0.0.0.0'

# - name: Starting {{component}} Service
#   ansible.builtin.systemd:
#     name: redis 
#     state: started
#     enabled: yes
#     daemon_reload: yes

- name: configuring {{component}} Repository
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install {{component}} package
  ansible.builtin.package:
    name: redis-6.2.13
    state: present

- name: Enabling {{component}} visibility
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restarting {{component}} service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: started
    enabled: true
    daemon_reload: true
