

#Copying the repo from local machine 
- name: copy the {{component}} file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo
  

# installing DB
- name: installing {{component}}
  ansible.builtin.package:
    name: mongodb-org
    state: present 

- name: Replacing Ip for visibility in {{component}}
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restarting {{component}}
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: yes
    daemon_reload: yes

- name: Unarchive a file that needs to be downloaded (added in 2.0) on {{component}}
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/mongodb/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Injecting users schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes
  
# - name: Injecting users and catalogue schema
#   community.mongodb.mongodb_shell:
#     file: "/tmp/mongodb-main/catalogue.js"
#     idempotent: yes