- name: Working on Global and local variables
  hosts: all
  vars:
    url: www.yahoo.com


  tasks:
      - name: printing local variable
        ansible.builtin.debug:
          msg: I have my emailID on {{url}}


      - name: printing local variable
        ansible.builtin.debug:
          msg: Can you please look into the site {{abc}}
        
        vars:
          abc: www.rediffmail.com