- name: creating directory
  hosts: all
  
  tasks:
    - name: play 01
      ansible.builtin.file:
        path: /tmp/ansible-demo
        state: directory
    

    - name: play 02
      ansible.builtin.file:
        path: /tmp/ansible-demo/{{ item }}
        state: touch 
      loop:
        - text23.txt
        - text45.txt       
        

    # - name: copying content
    #   ansible.builtin.copy:
    #     dest: /tmp/ansible-demo/text1.txt
    #     content:
    #           "Hello Everyone"   
            
 