- name: Demo on copying files
  hosts: all
  tasks:
    - name: Copying files
      ansible.builtin.copy:
        src: /home/centos/amlan.txt
        dest: /tmp/

- name: Copying another files
  hosts: all
  tasks:
    - name: copying another file to destn
      ansible.builtin.copy:
        src: /home/centos/kolkata.txt
        dest: /home/centos/