- name: Demo on privilege escalation
  hosts: all
  become: true
  tasks:
    - name: Demo on adding user
      user:
        name: "{{username}}"
        uid: "{{uid}}"
        state: present
      

    - name: Shell command for the user details
      ansible.builtin.shell: id {{username}}    #output of the shell command is stored in out variable
      register: out

    - name: printing user details
      ansible.builtin.debug:
        msg: "User details: {{out.stdout}}" #from out variable we are printing only stdout
  
      
