- name: "Play1"
  hosts: all
  vars:
    url: play.google.com
  vars_files:
    - "{{ENV}}.yaml"
  vars_files:
    - "{{PLACE}}.yaml"  

  tasks:
    - name: "printing global variable"
      ansible.builtin.debug:
        msg: "Hello the url is {{url}}" 

    - name: "printing unknown variable"
      ansible.builtin.debug:
        msg: "Hello the url is {{xyz}}"
      vars:
        xyz: "facebook.com"

    - name: "printing local variable"
      ansible.builtin.debug:
        msg: "Hello the url is {{abc}}"

      vars:
        abc: "Keep Working"

    - name: "Printing Specific value"
      ansible.builtin.debug:
        msg: "The Instace type is {{INSTANCE_TYPE}} and instance size is {{DISK_SIZE}}"
        
    - NAME: "Printing self stayed cities"
      ansible.builtin.debug:
        msg: "I stayed in {{CITY}} with location {{LOCATION}} of pincode {{PINCODE}}"    
             

      
 