- name: "Play1"
  hosts: all
  vars:
    url: play.google.com
  tasks:
    - name: "printing global variable"
      ansible.builtin.debug:
        msg: "Hello the url is {{url}}" 

    - name: "printing unknown variable"
      ansible.builtin.debug:
        msg: "Hello the url is {{xyz}}"
      vars:
        msg: "facebook.com"

 