- name: "Play1"
  hosts: all
  tasks:
    - name: "printing task1 of play1"
      ansible.builtin.debug:
        msg: "Hello from task1 of play1"

    - name: "Printing Local Variable"
      ansible.builtin.debug:
        msg: "The value is {{amlan}}"
      vars:
        amlan: "ping.google.com"

    - name: "Executing shell command"
      ansible.builtin.shell: "uptime"
      register: output

    - name: "Printing shell output"
      ansible.builtin.debug:
        msg: The result is {{output}}""
