- name: Demo on creating files
  hosts: all
  tasks: 
    - name: Creating files
      ansible.builtin.file:
        path: /tmp/dasa.txt
        state: touch
        mode: u+rx,g+rx,o-rx

    - name: creating directory
      ansible.builtin.file:
        path: /tmp/devdir
        state: directory
        mode: '0755'  

    - name: creating file
      ansible.builtin.file
        path: /home/centos/peacock.txt
        state: touch
        mode: '0644'
