- name: "Play1"
  hosts: all
  tasks:
    - name: "printing task1 of play1"
      ansible.builtin.debug:
        msg: "Hello from task1 of play1"

    - name: "Printing Local Variable"
      ansible.builtin.debug:
        msg: "The value is {{amlan}}"
      vars:
        amlan: "ping.google.com"

    - name: "Executing shell command"
      ansible.builtin.shell: "uptime"
      register: output

    - name: "Printing shell output"
      ansible.builtin.debug:
        msg: "The result is {{output.stdout}}"

    - name: "printing the Variable"
      ansible.builtin.debug:
        msg: "The value is {{xyz}}"
      vars:
       xyz: "Odd or Even"
      
     - name: "Printing variable as playbook1"
       ansible.builtin.debug:
          msg: "Welcome {{output1}} to the state {{output2}}"
       vars:
          output1: "Amlan Das"
          output2: "Karnataka" 