- name: Demo on priniting variable
  hosts: all
  vars:
    url: play.google.com      # Declaring variable at global level
  tasks:
    - name: printing the variable
      ansible.buletin.debug:
        msg: "the value is {{vars}}"
