- name: Demo on installing packages
  hosts: all
  become: True
  tasks:
    - name: Installing packages httpd and MariaDB
      ansible.builtin.debug:
        name: 
          - httpd
          - MariaDB
        state: present