- name: Demo on installing package
  hosts: all
  become: true
  tasks:
    - name: Installing httpd
      ansible.builtin.package:
        name: 
          - httpd
          - nginx
          - jq
        state: present