- name: "Play1"
  hosts: all
  vars:
    url: play.google.com
  tasks:
    - name: "printing global variable"
      ansible.builtin.debug:
        msg: "Hello the url is {{url}}" 

    - name: "printing unknown variable"
      ansible.builtin.debug:
        msg: "Hello the url is {{xyz}}"
      vars:
        xyz: "facebook.com"

    - name: "printing local variable"
      ansible.builtin.debug:
        msg: "Hello the url is {{abc}}"

      vars:
        abc: "Keep Working"

    - name: "Printing command line variable"
      ansible.buletin.debug
        msg: "The output url is {{pqr}}"      

      
 