- name: creating directory
  hosts: all
  
  tasks:
    - name: play 01
      ansible.builtin.file:
        path: /tmp/ansible-demo
        state: directory
    

    - name: play 02
      ansible.builtin.file:
        path: /tmp/ansible-demo/text1.txt
        state: touch        

    - name: play 03
      ansible.builtin.debug:
        msg: "Welcome to Ansible world"
        register: out    
    
    - name: play 04
      set_fact:
        EXITCODE= "{{out.rc}}"

    - name: play 05
      ansible.builtin.copy:
        src: "{{EXITCODE}}"
        dest: /tmp/ansible-demo/text1.txt    