- name: creating directory
  hosts: all
  
  tasks:
    - name: play 01
      ansible.builtin.file:
        path: /tmp/ansible-demo
        state: directory
    

    - name: play 02
      ansible.builtin.file:
        path: /tmp/ansible-demo/text1.txt
        state: touch        

    - name: Get uptime information
      ansible.builtin.shell: echo "Hello Everyone"
      register: result

    - name: Print return information from the previous task
      ansible.builtin.debug:
      var: 
        abc: result

    - name: play 05
      ansible.builtin.copy:
        src: "{{abc}}"
        dest: /tmp/ansible-demo/text1.txt    