- name: creating directory
  hosts: all
  
  tasks:
    - name: play 01
      ansible.builtin.file:
        path: /tmp/ansible-demo
        state: directory
    

    - name: play 02
      ansible.builtin.file:
        path: /tmp/ansible-demo/text1.txt
        state: touch        
        

    - name: copying content
      ansible.builtin.copy:
        dest: /tmp/ansible-demo/text1.txt
        content:
              "Hello Everyone"   
            
 