# Installing nginx
- name: Installing nginx
  ansible.builtin.package:
    name: nginx
    state: present
#Starting nginx service
- name: starting nginx
  ansible.builtin.service:
    name: nginx 
    state: started

#Download and unarchive the file
- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://example.com/example.zip
    dest: /usr/local/bin
    remote_src: yes