# Installing nginx
- name: Installing nginx
  ansible.builtin.package:
    name: nginx
    state: present
#Starting nginx service
- name: starting nginx
  ansible.builtin.service:
    name: nginx 
    state: started
    
# #Download and unarchive the file
- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/{{component}}/archive/main.zip"
    dest: /tmp
    remote_src: yes