
#1.Installing nginx package
- name: Installing nginx
  ansible.builtin.package:
    name: nginx
    state: present

#2.Starting the nginx service
- name: Start service nginx
  ansible.builtin.service:
    name: nginx
    state: started

#3.Downloading the archive file, unarchive the file and send to dest. All this are performed in remote machine
- name: Downloading and Extracting
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{component}}/archive/main.zip
    dest: /tmp/
    remote_src: yes 

#4.Cleaning the existing files
#- name: Remove file (delete file)
#  ansible.builtin.file:
#    path: /etc/foo.txt/usr/share/nginx/html
#    state: absent