# Installing nginx
- name: Installing nginx
  ansible.builtin.package:
    name: nginx
    state: present
#Starting nginx service
- name: starting nginx
  ansible.builtin.service:
    name: nginx 
    state: started

# #Download and unarchive the file
- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/{{component}}/archive/main.zip"
    dest: /tmp
    remote_src: yes

# Removing files from 
- name: Remove file (delete file)
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent    

#copying files
- name: copying files
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

#copying roboshop.conf file which is available in local machine. So no need to use remote_src
- name: copying files
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  