- name: Configuring nodesjs
  ansible.builtin.shell: yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
  ignore_errors: true

- name: Installing {{component}} package
  ansible.builtin.package:
    name: nodejs
    state: present 

- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: "{{appuser}}"

- name: Download and extracting {{component}}
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{component}}/archive/main.zip
    dest: /tmp
    remote_src: yes   

- name: Cleanup existing components
  ansible.builtin.file:
    path: /home/{{appuser}}/{{component}}
    state: absent

- name: Copying file
  ansible.builtin.copy:
    src: /tmp/{{component}}-main/*
    dest: /home/{{appuser}}/{{component}}/
    owner: "{{appuser}}"
    group: "{{appuser}}"
    remote_src: yes 

# - name: generating artifacts
#   community.general.npm:
#       path: /home/{{appuser}}/{{component}}/

# - name: copying systemd.service file
#   ansible.builtin.template:
#     src: systemd.service
#     dest: /etc/systemd/system/{{component}}.service

# - name: Restarting {{component}} service
#   ansible.builtin.systemd:
#     name: "{{component}}"
#     state: restarted
#     enabled: true
#     daemon_reload: true

