- name: Configuring nodesjs
  ansible.builtin.shell: yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
  remote_src: yes
  
- name: Installing {{component}} package
  ansible.builtin.package:
    name: nodejs
    state: present 

- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: "{{appuser}}"

- name: Download and extracting {{component}}
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{component}}/archive/main.zip
    dest: /tmp
    remote_src: yes   

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /home/{{appuser}}/{{component}}
    state: absent

- name: Copying file
  ansible.builtin.copy:
    src: /tmp/{{component}}-main
    dest: /home/{{appuser}}/{{component}}/
    owner: "{{appuser}}"
    group: "{{appuser}}"
    remote_src: yes 

